// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account/login": {
            "post": {
                "description": "账号登录",
                "tags": [
                    "account"
                ],
                "summary": "账号登录",
                "parameters": [
                    {
                        "description": "账号登录",
                        "name": "loginReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proto.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录tk",
                        "schema": {
                            "$ref": "#/definitions/proto.LoginResp"
                        }
                    }
                }
            }
        },
        "/account/sign_up": {
            "post": {
                "description": "注册账号",
                "tags": [
                    "account"
                ],
                "summary": "注册账号",
                "parameters": [
                    {
                        "description": "注册账号",
                        "name": "signInArgs",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/proto.SignUpArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录tk",
                        "schema": {
                            "$ref": "#/definitions/proto.LoginResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "proto.LoginReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "proto.LoginResp": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "proto.SignUpArgs": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "注册邮箱",
                    "type": "string"
                },
                "facebook_id": {
                    "description": "facebook的三方账号",
                    "type": "string"
                },
                "gooleplus_id": {
                    "description": "google+的三方账号",
                    "type": "string"
                },
                "password": {
                    "description": "用户密码",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
